config/routes.rb
Rails.application.routes.draw do
  

  get'tax_collected_in_the_year/check_the_year'

 #routes to check the admin and to get the data according to the city
  get 'check/for_super_admin'
  get 'check/search'
  get 'check/for_supervisor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' #routs for the admin pannel
  
  resources :rules,:properties #for all models
  


  #for the admin to add new users
  get  'employees/new',  to: 'welcome#new'
  post 'employees',  to: 'welcome#add_user'
  get  'users' ,to: 'welcome#index'
  
  devise_for :users  #fro the devise gem 
  
  #buttens for propwerty tax paied or not 
  post 'properties/pay_tax/:id' ,to: 'properties#pay_tax'
  post 'properties/check_if_payed/:id' ,to: 'properties#check_if_payed'
 
  # send tax demand notice button  
  post 'properties/:id' ,to: 'properties#ask_to_pay_tax'
 
   # for the home page 
  get 'home/index'
  root 'home#index'

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :User
  has_one_attached :image
  # geocoded_by :Address
  # after_validation :geocode
  validates :Owner,:Type_of_property, :Size_of_property, :State, :District, :Cost,:image,:Tax, :User_id,:Address, presence: true

 def self.search(search)
 	if search
 		@Property=Property.where(District:search)
 	else
    	@Property=Property.all
    end

 end
 def self.search1(search1)
 	if search1
 		search1=DateTime.parse(search1)
 		rang = search1.beginning_of_year..search1.end_of_year
 	    @Properties=Property.where(created_at:rang)
 	else
 		@Properties=Property.all
 	end
 end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:check_if_payed,:ask_to_pay_tax,:pay_tax,:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :authenticate_user!
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end


  def ask_to_pay_tax
    UserMailer.send_tax_notice(@property).deliver
    flash[:notice] = "Email has been sent."
    redirect_to property_path(@property)
    
  end
  def pay_tax
    @munth  = @property.Tax
    @quater = @munth*3
    @yearly = @quater*4
  end
  
  def check_if_payed
    @property.payed = true
    UserMailer.tax_payment_ricept(@property).deliver_later
    @property.save
    
    render'show'
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create

    # render plain: params[:property].inspect    
    @property = Property.new(property_params)
    @property.User_id=current_user.id
    @rule=Rule.where(Type_of_property:@property.Type_of_property,Size_of_property:@property.Size_of_property,State:@property.State,District:@property.District).take
    @property.Tax=(@property.Cost*@rule.Tax)/100
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:search,:Owner,:Type_of_property, :Size_of_property, :State, :District, :Cost,:image,:Tax, :User_id,:Address,:longitude,:latitude)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<style type="text/css">
  input{
    width: 70%;
    position: relative;
    left: 20%;
    /*padding-top: 10px;*/
    padding-bottom: 10px;
    border: none;
    border-bottom: 2px #948f86 dotted;
    background-color: transparent;
  }
  label{
    position: relative;
    /*left: 13%;*/
    top: 20px;
    margin-top: 3%;
    font-size: 17px;
    font-family: cursive;
  }
  .actions>input{
    /*background-color: red;*/
    width: 12%;
    color: #383734
    font-size: 18px;
    /*background-image: repeating-linear-gradient(45deg, yellow, wheat 100px);*/
    font-weight: 600;
    border: double;
    border-radius: 20%;
    position: relative;
    left: 20%;
    margin-top: 5%;
    padding-bottom: 0;
  }
  select{
    position: relative;
    left: 20%;
    width: 70%;
    background-color: transparent;
    border: none;
    border-bottom: dotted;
  }
</style>




<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Image %>
    <%= form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :Type_of_property %>
    <%= form.select(:Type_of_property, [['commercial'], ['semi_commercial'], ['non-commercial']]) %>
  </div>

  <div class="field">
    <%= form.label :Size_of_property %>
    <%= form.select(:Size_of_property, [['Large'], ['Medium'], ['small']]) %>
    
  </div>

  <div class="field">
    <%= form.label :State %>
    <%= form.text_field :State %>
  </div>

  <div class="field">
    <%= form.label :District %>
    <%= form.text_field :District %>
  </div>

  <div class="field">
    <%= form.label :Cost %>
    <%= form.text_field :Cost %>
  </div>


  <div class="field">
    <%= form.label :Owner %>
    <%= form.email_field :Owner %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Properties</h1>
<div>
<br><br>
<div class="states">
<%if current_user.superadmin_role%>
    <%=form_tag check_search_path ,method: "get" do%>
    <%=text_field_tag :search , params[:search]%>
    <%=submit_tag("search",:name => nil)%>
    <%end%>
<%end%>

<br>
</div>
<div class="states">
<br>

<br><br>
<%if current_user.superadmin_role%>
    <%=form_tag tax_collected_in_the_year_check_the_year_path ,method: "get" do%>
    <%=label_tag :enter_the_year_you_want_to_cheack%>
    <%=datetime_local_field_tag :search1 , params[:search1]%>
    <%=submit_tag("search",:name => nil)%>
    <%end%>
<%end%>

<br>
</div>
<br>
</div>



<table>
  <thead>
    <tr>
      <th>Date of creation </th>
      <th>Owner</th>
      <th>Type of property</th>
      <th>Size of property</th>
      <th>State</th>
      <th>District</th>
      <th>Cost</th>
      <th>Tax</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
        <tr>
      <%if current_user.superadmin_role||current_user.id == property.User_id||current_user.email==property.Owner%>

        <td><%= property.created_at.year %></td>
        <td><%=property.Owner.split("@")[0]%></td>
        <td><%= property.Type_of_property %></td>
        <td><%= property.Size_of_property %></td>
        <td><%= property.State %></td>
        <td><%= property.District %></td>
        <td><%= property.Cost %></td>
        <td><%= property.Tax %></td>
        <td><%= property.User_id %></td>

        <%if can? :read ,property%>
        <td><%=button_to 'Show', property %></td>
        <%end%>  
        
       

       <%if current_user.superadmin_role||current_user.id==property.User_id%>

        <%if can? :update ,property%>
        <td><%=link_to 'Edit', edit_property_path(property) %></td>
        <%end%>
        
        <%if can? :delete ,property%>
        <td><%=button_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        <%end%>
       <%end%>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%if current_user.superadmin_role%>
<div>
<h1>states:-</h1>
  <div class="states"><%=pie_chart Property.group(:Payed).count ,donut:true,colors:[:wheat]%>
 </div>
  <div class="states"><%=column_chart Property.group(:Payed).count,colors:[:wheat] %>
  <h3 style="text-align: center;">Payments Done</h3>
</div>
</div>
<%end%>


<%if current_user.superadmin_role?||current_user.supervisor_role?%>
  <%=link_to 'New Property', new_property_path %>
<%end%>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/pay_tax.html.erb
<style type="text/css">
    td{
        height: 200px;
        font-size: 27px;
    font-family: fantasy;
    color: darkgrey;
    }
    .first{
        /*text-align: center;*/
        position: relative;
    
    top: 34px;
    }
</style>
<div class="first">
<table>
	<tr>
		<th>monthly</th>
		<th>quaterly</th>
		<th>yearly</th>
	</tr>

    <tr>
    	<td><%=@munth%><p>
        <%= button_to "pay_tax", { :controller => "properties", :action => "check_if_payed"}%>
</p></td>
    	<td><%=@quater%><p>
        <%= button_to "pay_tax", { :controller => "properties", :action => "check_if_payed"}%>
</p></td>
    	<td><%=@yearly%><p>
        <%= button_to "pay_tax", { :controller => "properties", :action => "check_if_payed"}%>
</p></td>

    </tr>
    

</table>
<!-- </div> -->

</div>

app/views/properties/show.html.erb
<head>
    <style>
       /* Set the size of the div element that contains the map */
      #map {
        height: 200px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
       span>img{
            height: 247px;
            width: 100%;
            /*position: relative;*/
            /*left: 11%;*/

         }
         .butn{
          position: relative;
          left: 46%;
          margin-top: 5%;
         }
    </style>
  </head>
  
    <h3>My Google Maps Demo</h3>
    <!--The div element for the map -->
    <div id="map"></div>
    <script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  // var uluru = {lat: @property.latitude, lng: longitude};
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDX9B7R-SncLDb8w_Dlj8fOJRJp_5rlBtA&callback=initMap">
    </script>
  




<br>








<p>
  <strong>Image:</strong>
  
<span><%= image_tag(@property.image) %></span>
  
</p>


<table>
  <tr>
    <th>Categorys</th>
    <th>Details</th>
  </tr>

  <tr>
    <td>  <strong>Owner</strong></td>
    <td> <%=  @property.Owner.split("@")[0] %></td>
  </tr>
  <tr>
      <td>  <strong>Type of property</strong></td>
      <td>  <%= @property.Type_of_property %></td>
  </tr>
  <tr>
      <td><strong>Size of property</strong></td>
      <td><%= @property.Size_of_property %></td>
  </tr>
  <tr>
      <td><strong>State</strong></td>
      <td> <%= @property.State %></td>
  </tr>
  <tr>
      <td> <strong>District</strong></td>
      <td><%= @property.District %></td>
  </tr>
  <tr>
      <td><strong>Cost</strong></td>
      <td><%= @property.Cost %></td>
  </tr>
  <tr>
      <td><strong>Tax</strong></td>
      <td> <%= @property.Tax %>
        <%if @property.payed%> <br>(Payed)<%else%> <br>(Not-Payed)<%end%>
      </td>
  </tr>
  <tr>
      <td><strong>Address</strong></td>
      <td><%= @property.Address %></td>
  </tr>
  <tr>
    <td><strong>User</strong></td>
    <td><%= @property.User_id%></td>
  </tr>

</table>


  

 





<%if current_user.superadmin_role? || current_user.supervisor_role?%>
        <div class="butn"><%= button_to "Send Notice", { :controller => "properties", :action => "ask_to_pay_tax"}%></div>
<%end%> 
<!-- http://localhost:3000/rails/mailers/user_mailer/send_tax_notice      to access the preview-->

<%if current_user.user_role?%>
<%if @property.payed%>(Payed)
<%else%>
<p><%= button_to "pay_tax", { :controller => "properties", :action => "pay_tax"}%><%end%>
<%end%></p>
<%if current_user.superadmin_role||current_user.supervisor_role%>
<p style="float: right;"><%= link_to 'Edit', edit_property_path(@property) %></p> 
<%end%>
<%= link_to 'Back', properties_path %>