config/routes.rb
Rails.application.routes.draw do
  

  get'tax_collected_in_the_year/check_the_year'

 #routes to check the admin and to get the data according to the city
  get 'check/for_super_admin'
  get 'check/search'
  get 'check/for_supervisor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' #routs for the admin pannel
  
  resources :rules,:properties #for all models
  


  #for the admin to add new users
  get  'employees/new',  to: 'welcome#new'
  post 'employees',  to: 'welcome#add_user'
  get  'users' ,to: 'welcome#index'
  
  devise_for :users  #fro the devise gem 
  
  #buttens for propwerty tax paied or not 
  post 'properties/pay_tax/:id' ,to: 'properties#pay_tax'
  post 'properties/check_if_payed/:id' ,to: 'properties#check_if_payed'
 
  # send tax demand notice button  
  post 'properties/:id' ,to: 'properties#ask_to_pay_tax'
 
   # for the home page 
  get 'home/index'
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%if current_user.supervisor_role?%>
<style type="text/css">
  .main_section{
    position: relative;
    top: 0px;
    display: inline-block;
    height: 470px;
    width: 71%;
    background-color: #ffdeb175;
  }
</style>
<%end%>
<%if current_user.user_role?%>
<style type="text/css">
  .side_section {
    position: relative;
    top: -170px;
    display: inline-block;
    width: 28%;
    background: #efe8d0;
    text-align: center;
    height: 475px;
    background-image: repeating-linear-gradient(90deg, wheat, transparent 259px);
}
.main_section {
    position: relative;
    top: 0px;
    display: inline-block;
    height: 477px;
    width: 71%;
    background-color: #ffdeb175;
}
</style>
<%end%>
<div class="container_in_home">
  <div  class="side_section">

          <%if current_user%>
             
             <%=link_to'Sign Out',destroy_user_session_path ,method: :delete%><br><br>
             <%= link_to 'Change Password', edit_user_registration_path %><br><br>
             <%=link_to'Properties',properties_path%><br><br>
             <%=link_to'Rules',rules_path%> <br><br>
             
              <%if current_user.superadmin_role? %>
                  <%=link_to'Admin Panal',rails_admin_path%><br><br>
                  <%=link_to'Collection',check_for_super_admin_path%><br><br>
              <%end%>  
              <%if current_user.supervisor_role? %>
                   <%=link_to'Collection',check_for_supervisor_path%><br><br>
              <%end%>

              <%if current_user.superadmin_role? || current_user.supervisor_role? %>
                   <%=link_to'Users List',users_path%><br><br>
                   <%=link_to'Add User',employees_new_path%><br><br>
              <%end%>  

          <%else%>
               <%=link_to'sign_in',new_user_session_path%><br><br>
          <%end%>

   </div>
   <div class="main_section">
       <div class="image_at_home"><%=image_tag("tax.png")%></div>
       <div class="first_para">
         <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

         <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

       </div>
   </div>
 </div>