config/routes.rb
Rails.application.routes.draw do
  

  get'tax_collected_in_the_year/check_the_year'

 #routes to check the admin and to get the data according to the city
  get 'check/for_super_admin'
  get 'check/search'
  get 'check/for_supervisor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin' #routs for the admin pannel
  
  resources :rules,:properties #for all models
  


  #for the admin to add new users
  get  'employees/new',  to: 'welcome#new'
  post 'employees',  to: 'welcome#add_user'
  get  'users' ,to: 'welcome#index'
  
  devise_for :users  #fro the devise gem 
  
  #buttens for propwerty tax paied or not 
  post 'properties/pay_tax/:id' ,to: 'properties#pay_tax'
  post 'properties/check_if_payed/:id' ,to: 'properties#check_if_payed'
 
  # send tax demand notice button  
  post 'properties/:id' ,to: 'properties#ask_to_pay_tax'
 
   # for the home page 
  get 'home/index'
  root 'home#index'

end

app/models/rule.rb
class Rule < ApplicationRecord
	validates :Type_of_property, :Size_of_property, :State, :District, :frequency, :Tax, presence: true
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :authenticate_user!
  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
   
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rule_params
      params.require(:rule).permit(:Type_of_property, :Size_of_property, :State, :District, :frequency, :Tax)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<style type="text/css">
  input{
    width: 70%;
    position: relative;
    left: 20%;
    /*padding-top: 10px;*/
    padding-bottom: 10px;
    border: none;
    border-bottom: 2px #948f86 dotted;
    background-color: transparent;
  }
  label{
    position: relative;
    /*left: 13%;*/
    top: 20px;
    margin-top: 3%;
    font-size: 17px;
    font-family: cursive;
  }
  .actions>input{
    /*background-color: red;*/
    width: 12%;
    color: #383734
    font-size: 18px;
    /*background-image: repeating-linear-gradient(45deg, yellow, wheat 100px);*/
    font-weight: 600;
    border: double;
    border-radius: 20%;
    position: relative;
    left: 20%;
    margin-top: 5%;
    padding-bottom: 0;
  }
  select{
    position: relative;
    left: 20%;
    width: 70%;
    background-color: transparent;
    border: none;
    border-bottom: dotted;
  }
</style>


<%= form_with(model: rule, local: true) do |form| %>
  <% if rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
        <% rule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Type_of_property %>
    <%= form.select(:Type_of_property, [['commercial'], ['semi_commercial'], ['non-commercial']]) %>
  </div>

  <div class="field">
    <%= form.label :Size_of_property %>
    <%= form.select(:Size_of_property, [['Large'], ['Medium'], ['small']]) %>
    
  </div>

  
  <div class="field">
    <%= form.label :State %>
    <%= form.text_field :State %>
  </div>

  <div class="field">
    <%= form.label :District %>
    <%= form.text_field :District %>
  </div>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.select(:frequency, [['monthly',1], ['quaterly',3], ['yearly',12]]) %>

  </div>

  <div class="field">
    <%= form.label :Tax %>
    <%= form.text_field :Tax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing Rule</h1>

<%= render 'form', rule: @rule %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Rules</h1>

<table>
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Type of property</th>
      <th>Size of property</th>
      <th>State</th>
      <th>District</th>
      <th>Frequency</th>
      <th>Tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
     
     <tr>
        <td><%=rule.created_at.year%></td>
        <td><%= rule.Type_of_property %></td>
        <td><%= rule.Size_of_property %></td>
        <td><%= rule.State %></td>
        <td><%= rule.District %></td>
        <td><%= rule.frequency %></td>
        <td><%= rule.Tax %></td>
       
        <%if can? :read ,rule%>
        <td><%= link_to 'Show', rule %></td>
        <% end %>
       
        <%if can? :update ,rule%>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <% end %>
       
        <%if can? :delete ,rule%>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if current_user.superadmin_role?||current_user.supervisor_role?%>
<%if current_user.superadmin_role%><%= link_to 'New Rule', new_rule_path %><%end%>
<%end%>

app/views/rules/new.html.erb
<h1>New Rule</h1>

<%= render 'form', rule: @rule %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<style type="text/css">
  table{
   position: relative;
    left: 15%; 

  }
</style>
<table >
  <tr>
    <th>Categorys</th>
    <th>Details</th>
  </tr>

  
  <tr>
      <td>  <strong>Type of property</strong></td>
      <td>  <%= @rule.Type_of_property %></td>
  </tr>
  <tr>
      <td><strong>Size of property</strong></td>
      <td><%= @rule.Size_of_property %></td>
  </tr>
  <tr>
      <td><strong>State</strong></td>
      <td> <%= @rule.State %></td>
  </tr>
  <tr>
      <td> <strong>District</strong></td>
      <td><%= @rule.District %></td>
  </tr>
  
  <tr>
      <td><strong>Tax</strong></td>
      <td> <%= @rule.Tax %>%</td>
  </tr>
  <tr>
    <td><strong>Frequency:</strong></td>
    <td><%= @rule.frequency %></td>
  </tr>
</table>







<%if current_user.superadmin_role%>
<p style="float: right;"><%= link_to 'Edit', edit_rule_path(@rule) %></p>
<%end%>
<%= link_to 'Back', rules_path %>